/**
 * mmm-raw-instructions.ts — offline test suite.
 *
 * No live network calls. The `REAL_*` fixture constants below were
 * captured ONCE via a bounded, read-only `getTransaction` /
 * `getAccountInfo` call against a real, independently-selected historical
 * MMM `create_pool` transaction (signature
 * `3zZzjVEZiNMWH8mfsDFYL9woP2VhM9BKHqbmta8iHai26iGsXngWGSqsrw2jBVzaECTR5aBVtPgVM2vNJ7FTDmxa`,
 * pool `9FJCWoGf8hZKRrbq3pwKcPrcs5kZuN5gjqBYn1YiYrpe`) and its bundled
 * `sol_deposit_buy` instruction, plus the pool account's later on-chain
 * state — this is evidence independent of `mmm-raw-instructions.ts`'s own
 * implementation, not a fixture generated by the code under test.
 *
 * Convention matches src/server/__tests__/tools-me-bids.test.ts: ts-node +
 * Node's built-in `assert`, a running failure counter, `process.exit`.
 *
 * Run: `npm run test:mmm-collection-bids-raw`.
 */

import assert from 'assert';
import { PublicKey, Keypair } from '@solana/web3.js';
import {
  MMM_PROGRAM_ID, MMM_DISCRIMINATORS, CURVE_KIND_LINEAR, CURVE_KIND_EXP,
  ALLOWLIST_KIND, ALLOWLIST_MAX_LEN, POOL_ACCOUNT_SIZE,
  derivePoolPda, deriveEscrowPda, normalizeAllowlists, generatePoolUuid,
  buildCreatePoolIx, buildUpdatePoolIx, buildSolDepositBuyIx, buildSolWithdrawBuyIx,
  buildSolClosePoolIx, decodePool,
} from '../mmm-raw-instructions';

let failures = 0;
let passed = 0;
function check(label: string, fn: () => void): void {
  try { fn(); passed++; console.log(`  ok - ${label}`); }
  catch (err) { failures++; console.error(`  FAIL - ${label}\n     ${(err as Error).message}`); }
}

// ── Real historical fixture (independently captured, see header) ────────

const REAL_OWNER = 'Xqm84Q2LGZJaJ96hUQLoxhuqTUZzT6odGH18UxnccnT';
const REAL_COSIGNER = 'NTYeYJ1wr4bpM5xo6zx5En44SvJFAd35zTxxNoERYqd';
const REAL_POOL = '9FJCWoGf8hZKRrbq3pwKcPrcs5kZuN5gjqBYn1YiYrpe';
const REAL_ESCROW = 'BABZWfhvY8KsftKpiUEkExpEKy4FEm2eTzQSwnnHb3tN';
const REAL_UUID = 'BHNhgtkQTyseL6BuXDN99pHuDsEXDcgmfAXikW4CRNcD';
const REAL_REFERRAL = '8d7dmXFxP9YKubdfo3JeFYUYfC1C65HHtw9tAGsg934z';
const REAL_ALLOWLIST_VALUE = 'G3uz4QgSbPFxmCc29YjoE9A1T8BBtJSFSNsb1ZJt4Gzw';
const REAL_COSIGNER_ANNOTATION_HEX = 'df9e5fdc4b7cc6c6a3785c5d8098c5b13efe19d87b11cab8ba52460b2cfb6484';
if (REAL_COSIGNER_ANNOTATION_HEX.length !== 64) throw new Error('fixture_annotation_hex_wrong_length');

const REAL_CREATE_IX_DATA_HEX = 'e992d18ecf6840bc40f9781100000000012c01000000000000000000000000000000000000714237f70c467e0b3a7a0efebea498a134eb533c26c9d7047172e1935743f25fdf9e5fdc4b7cc6c6a3785c5d8098c5b13efe19d87b11cab8ba52460b2cfb6484102798c6b33f8e4e3cfb3001090a7969442af2ebcb44341079a4932f8a99675e41fe000000000000000000000000000000000000000000000000000000000000000001df9e5fdc4b7cc6c6a3785c5d8098c5b13efe19d87b11cab8ba52460b2cfb6484000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000';

const REAL_CREATE_IX_ACCOUNTS = [REAL_OWNER, REAL_COSIGNER, REAL_POOL, '11111111111111111111111111111111'];

const REAL_DEPOSIT_IX_DATA_HEX = '42e50b366da455ee9daa6f2200000000';
const REAL_DEPOSIT_IX_ACCOUNTS = [REAL_OWNER, REAL_COSIGNER, REAL_POOL, REAL_ESCROW, '11111111111111111111111111111111'];
const REAL_DEPOSIT_AMOUNT_LAMPORTS = 577_743_517n;

const REAL_POOL_ACCOUNT_HEX = 'f19a6d0411b16dbc5eb1f61000000000012c01000000000000000000000000000000000000714237f70c467e0b3a7a0efebea498a134eb533c26c9d7047172e1935743f25f00001027df9e5fdc4b7cc6c6a3785c5d8098c5b13efe19d87b11cab8ba52460b2cfb64840000000000000000000000000000000007e68ee5bb9a0142ed674e9b768a2e54d5ea56ba432cdb2b60fa6a83fc078920057f36559928ce1babadb65b8b5d9e31ba27f8539bec602ccb1adc2afb9f467098c6b33f8e4e3cfb3001090a7969442af2ebcb44341079a4932f8a99675e41fe000000000000000000000000000000000000000000000000000000000000000001df9e5fdc4b7cc6c6a3785c5d8098c5b13efe19d87b11cab8ba52460b2cfb64840000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005db1f6100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000';

function pubkey(s: string): PublicKey { return new PublicKey(s); }

// ── PDA derivation ───────────────────────────────────────────────────────

check('derivePoolPda matches the real historical pool address', () => {
  const derived = derivePoolPda(pubkey(REAL_OWNER), pubkey(REAL_UUID));
  assert.strictEqual(derived.toBase58(), REAL_POOL);
});

check('deriveEscrowPda matches the real historical escrow address', () => {
  const derived = deriveEscrowPda(pubkey(REAL_POOL));
  assert.strictEqual(derived.toBase58(), REAL_ESCROW);
});

check('derivePoolPda changes with a different uuid (salt actually used)', () => {
  const a = derivePoolPda(pubkey(REAL_OWNER), pubkey(REAL_UUID));
  const b = derivePoolPda(pubkey(REAL_OWNER), generatePoolUuid());
  assert.notStrictEqual(a.toBase58(), b.toBase58());
});

check('derivePoolPda changes with a different owner', () => {
  const other = Keypair.generate().publicKey;
  const a = derivePoolPda(pubkey(REAL_OWNER), pubkey(REAL_UUID));
  const b = derivePoolPda(other, pubkey(REAL_UUID));
  assert.notStrictEqual(a.toBase58(), b.toBase58());
});

// ── create_pool: byte-exact against the real captured instruction ───────

check('buildCreatePoolIx: byte-exact match against real historical create_pool data', () => {
  const ix = buildCreatePoolIx(
    { owner: pubkey(REAL_OWNER), cosigner: pubkey(REAL_COSIGNER), pool: pubkey(REAL_POOL) },
    {
      spotPriceLamports: 293_140_800n,
      curveType: CURVE_KIND_EXP,
      curveDelta: 300n,
      reinvestFulfillBuy: false,
      reinvestFulfillSell: false,
      expiry: 0n,
      lpFeeBp: 0,
      referral: pubkey(REAL_REFERRAL),
      cosignerAnnotation: Buffer.from(REAL_COSIGNER_ANNOTATION_HEX, 'hex'),
      buysideCreatorRoyaltyBp: 10_000,
      uuid: pubkey(REAL_UUID),
      allowlists: [{ kind: ALLOWLIST_KIND.FVCA, value: pubkey(REAL_ALLOWLIST_VALUE) }],
    },
  );
  assert.strictEqual(ix.data.toString('hex'), REAL_CREATE_IX_DATA_HEX);
});

check('buildCreatePoolIx: account order/signer/writable flags match the real tx exactly', () => {
  const ix = buildCreatePoolIx(
    { owner: pubkey(REAL_OWNER), cosigner: pubkey(REAL_COSIGNER), pool: pubkey(REAL_POOL) },
    {
      spotPriceLamports: 293_140_800n, curveType: CURVE_KIND_EXP, curveDelta: 300n,
      reinvestFulfillBuy: false, reinvestFulfillSell: false, expiry: 0n, lpFeeBp: 0,
      referral: pubkey(REAL_REFERRAL), cosignerAnnotation: Buffer.from(REAL_COSIGNER_ANNOTATION_HEX, 'hex'),
      buysideCreatorRoyaltyBp: 10_000, uuid: pubkey(REAL_UUID),
      allowlists: [{ kind: ALLOWLIST_KIND.FVCA, value: pubkey(REAL_ALLOWLIST_VALUE) }],
    },
  );
  assert.strictEqual(ix.programId.toBase58(), MMM_PROGRAM_ID.toBase58());
  assert.deepStrictEqual(ix.keys.map((k) => k.pubkey.toBase58()), REAL_CREATE_IX_ACCOUNTS);
  assert.deepStrictEqual(ix.keys.map((k) => k.isSigner), [true, true, false, false]);
  assert.deepStrictEqual(ix.keys.map((k) => k.isWritable), [true, false, true, false]);
});

check('buildCreatePoolIx: discriminator matches the source-verified value', () => {
  const ix = buildCreatePoolIx(
    { owner: pubkey(REAL_OWNER), cosigner: pubkey(REAL_COSIGNER), pool: pubkey(REAL_POOL) },
    {
      spotPriceLamports: 1n, curveType: CURVE_KIND_LINEAR, curveDelta: 0n,
      reinvestFulfillBuy: false, reinvestFulfillSell: false, expiry: 0n, lpFeeBp: 0,
      referral: PublicKey.default, cosignerAnnotation: Buffer.alloc(32), buysideCreatorRoyaltyBp: 0,
      uuid: pubkey(REAL_UUID), allowlists: [],
    },
  );
  assert.strictEqual(ix.data.subarray(0, 8).toString('hex'), MMM_DISCRIMINATORS.createPool.toString('hex'));
});

// ── sol_deposit_buy: byte-exact against the real bundled instruction ────

check('buildSolDepositBuyIx: byte-exact match against real historical deposit data', () => {
  const ix = buildSolDepositBuyIx(
    { owner: pubkey(REAL_OWNER), cosigner: pubkey(REAL_COSIGNER), pool: pubkey(REAL_POOL), escrow: pubkey(REAL_ESCROW) },
    REAL_DEPOSIT_AMOUNT_LAMPORTS,
  );
  assert.strictEqual(ix.data.toString('hex'), REAL_DEPOSIT_IX_DATA_HEX);
  assert.deepStrictEqual(ix.keys.map((k) => k.pubkey.toBase58()), REAL_DEPOSIT_IX_ACCOUNTS);
  assert.deepStrictEqual(ix.keys.map((k) => k.isSigner), [true, true, false, false, false]);
  assert.deepStrictEqual(ix.keys.map((k) => k.isWritable), [true, false, true, true, false]);
});

// ── decodePool: byte-exact against the real historical pool account ─────

check('decodePool: decodes the real 849-byte pool account without error', () => {
  const buf = Buffer.from(REAL_POOL_ACCOUNT_HEX, 'hex');
  assert.strictEqual(buf.length, POOL_ACCOUNT_SIZE);
  const decoded = decodePool(buf);
  assert.ok(decoded);
});

check('decodePool: owner/cosigner/uuid/referral/allowlist match the real create_pool args exactly', () => {
  const decoded = decodePool(Buffer.from(REAL_POOL_ACCOUNT_HEX, 'hex'))!;
  assert.strictEqual(decoded.owner, REAL_OWNER);
  assert.strictEqual(decoded.cosigner, REAL_COSIGNER);
  assert.strictEqual(decoded.uuid, REAL_UUID);
  assert.strictEqual(decoded.referral, REAL_REFERRAL);
  assert.strictEqual(decoded.curveType, CURVE_KIND_EXP);
  assert.strictEqual(decoded.curveDelta, 300n);
  assert.strictEqual(decoded.lpFeeBp, 0);
  assert.strictEqual(decoded.buysideCreatorRoyaltyBp, 10_000);
  assert.strictEqual(decoded.allowlists[0].kind, ALLOWLIST_KIND.FVCA);
  assert.strictEqual(decoded.allowlists[0].value.toBase58(), REAL_ALLOWLIST_VALUE);
  for (let i = 1; i < ALLOWLIST_MAX_LEN; i++) assert.strictEqual(decoded.allowlists[i].kind, ALLOWLIST_KIND.EMPTY);
});

check('decodePool: rejects a buffer of the wrong length', () => {
  assert.strictEqual(decodePool(Buffer.alloc(848)), null);
  assert.strictEqual(decodePool(Buffer.alloc(850)), null);
});

// ── Quantity model: delta=0 constant price, and quantity → liquidity ────

check('quantity model: price 0.0118 SOL x quantity 1 == 11_800_000 lamports', () => {
  const pricePerNft = 11_800_000n;
  assert.strictEqual(pricePerNft * 1n, 11_800_000n);
});
for (const qty of [2, 5, 10]) {
  check(`quantity model: price 0.0118 SOL x quantity ${qty}`, () => {
    const pricePerNft = 11_800_000n;
    assert.strictEqual(pricePerNft * BigInt(qty), 11_800_000n * BigInt(qty));
  });
}
check('curveDelta=0 (linear) implies a constant per-fill price regardless of k — matches listings-store.ts formula', () => {
  const spot = 11_800_000n;
  const delta = 0n;
  for (const k of [0n, 1n, 2n, 9n]) {
    const priceAtK = spot + delta * k; // linear formula, delta=0 collapses to spot
    assert.strictEqual(priceAtK, spot);
  }
});

// ── normalizeAllowlists ──────────────────────────────────────────────────

check('normalizeAllowlists pads to exactly ALLOWLIST_MAX_LEN entries', () => {
  const out = normalizeAllowlists([{ kind: ALLOWLIST_KIND.MCC, value: pubkey(REAL_ALLOWLIST_VALUE) }]);
  assert.strictEqual(out.length, ALLOWLIST_MAX_LEN);
  assert.strictEqual(out[0].kind, ALLOWLIST_KIND.MCC);
  for (let i = 1; i < ALLOWLIST_MAX_LEN; i++) assert.strictEqual(out[i].kind, ALLOWLIST_KIND.EMPTY);
});

check('normalizeAllowlists throws when given more than ALLOWLIST_MAX_LEN entries', () => {
  const many = Array.from({ length: ALLOWLIST_MAX_LEN + 1 }, () => ({ kind: ALLOWLIST_KIND.ANY, value: PublicKey.default }));
  assert.throws(() => normalizeAllowlists(many));
});

// ── update_pool / withdraw / close: account order + writable flags ──────

check('buildUpdatePoolIx: 3 accounts, no system_program, owner writable / cosigner readonly / pool writable', () => {
  const ix = buildUpdatePoolIx(
    { owner: pubkey(REAL_OWNER), cosigner: pubkey(REAL_COSIGNER), pool: pubkey(REAL_POOL) },
    {
      spotPriceLamports: 1n, curveType: CURVE_KIND_LINEAR, curveDelta: 0n, reinvestFulfillBuy: false,
      reinvestFulfillSell: false, expiry: 0n, lpFeeBp: 0, referral: PublicKey.default,
      cosignerAnnotation: Buffer.alloc(32), buysideCreatorRoyaltyBp: 0,
    },
  );
  assert.strictEqual(ix.keys.length, 3);
  assert.deepStrictEqual(ix.keys.map((k) => k.isSigner), [true, true, false]);
  assert.deepStrictEqual(ix.keys.map((k) => k.isWritable), [true, false, true]);
  assert.strictEqual(ix.data.subarray(0, 8).toString('hex'), MMM_DISCRIMINATORS.updatePool.toString('hex'));
});

check('buildSolWithdrawBuyIx: same 5-account shape as deposit, correct discriminator + amount', () => {
  const ix = buildSolWithdrawBuyIx(
    { owner: pubkey(REAL_OWNER), cosigner: pubkey(REAL_COSIGNER), pool: pubkey(REAL_POOL), escrow: pubkey(REAL_ESCROW) },
    123_456n,
  );
  assert.strictEqual(ix.data.subarray(0, 8).toString('hex'), MMM_DISCRIMINATORS.solWithdrawBuy.toString('hex'));
  assert.strictEqual(ix.data.readBigUInt64LE(8), 123_456n);
  assert.deepStrictEqual(ix.keys.map((k) => k.pubkey.toBase58()), [REAL_OWNER, REAL_COSIGNER, REAL_POOL, REAL_ESCROW, '11111111111111111111111111111111']);
});

check('buildSolClosePoolIx: 5 accounts, escrow read-only, no args beyond discriminator', () => {
  const ix = buildSolClosePoolIx({ owner: pubkey(REAL_OWNER), cosigner: pubkey(REAL_COSIGNER), pool: pubkey(REAL_POOL), escrow: pubkey(REAL_ESCROW) });
  assert.strictEqual(ix.data.toString('hex'), MMM_DISCRIMINATORS.solClosePool.toString('hex'));
  assert.deepStrictEqual(ix.keys.map((k) => k.isWritable), [true, false, true, false, false]);
});

console.log(`\n${passed} passed, ${failures} failed`);
if (failures > 0) process.exit(1);
